global using Xunit;
global using FluentAssertions;
global using NSubstitute;
global using NSubstitute.ReturnsExtensions;
global using BookwormsAPI.Contracts;
global using BookwormsAPI.Controllers;
global using BookwormsAPI.DTOs;
global using BookwormsAPI.Specifications;
global using BookwormsAPI.Entities;